CREATE USER 'app_user' IDENTIFIED BY 'password';
CREATE DATABASE IF NOT EXISTS app;
GRANT ALL PRIVILEGES ON app.* TO 'app_user';
CREATE DATABASE IF NOT EXISTS app_testing;
GRANT ALL PRIVILEGES ON app_testing.* TO 'app_user';
FLUSH PRIVILEGES;